# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e9ae3dd888351201ae285d98b53188f670ed2755e4c86d023ee95a417f8a1d135619dd43db086379bf807babbda389e529f6198b041bf4a9b42e7a080752b4

test:
  secret_key_base: 833ca181a43ef435048cd4a2daac62d32768886cd482f6c84e0f16a5d1db0bb293f3c3635827adfc3a80514a7862c8b25c5aca3cb7e5b8da692d48126cf68321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
